TARGETNAME := $(APP)

CONFIG_CLI := 1
CONFIG_MINIO := 1
CONFIG_FLASH := 1
CONFIG_GPIO := 1
#CONFIG_NVMTNV_JOURNAL := 1
CONFIG_RINGBUFFER := 1
CONFIG_UART := 1
CFLAGS += -DCONFIG_UART_STM32_RX_INTERRUPT

CFLAGS += -DCONFIG_CORTEX_HALT_USING_SYSCLK
CFILES += $(wildcard $(APP)/*.c)
CFILES += $(wildcard $(APP)/drivers/*.c)
INCLUDE += $(APP)

LINKER_FILES += $(APP)/$(APP).ld

LIBS += -Lgcc
