TARGETNAME := $(APP)

CONFIG_CLI := 1
CONFIG_MINIO := 1
CONFIG_FLASH := 1
CONFIG_GPIO := 1
#CONFIG_NVMTNV_JOURNAL := 1
CONFIG_RINGBUFFER := 1
CONFIG_TICK_TIMER := 1
CFLAGS += -DCONFIG_TICK_TIMER_STM32_HW_TIM=3 -DCONFIG_TICK_TIMER_STM32_PRESCALER=1099
CONFIG_UART := 1
CFLAGS += -DCONFIG_UART_STM32_RX_INTERRUPT

CFLAGS += -DCONFIG_CORTEX_HALT_USING_SYSCLK
CFILES += $(wildcard $(APP)/*.c)
CFILES += $(wildcard $(APP)/fonts/*.c)
CFILES += $(wildcard $(APP)/ui/*.c)
INCLUDE += $(APP)
INCLUDE += $(APP)/fonts
INCLUDE += $(APP)/ui

LINKER_FILES += $(APP)/$(APP).ld

LIBS += -Lgcc
